name: Lint

description: This action will lint the application code.

inputs:
  node-version:
    description: 'The version of node to use'
    required: true
    default: '20.11.1'

runs:
  using: 'composite'
  permissions:
    contents: write # This is required to commit changes
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      shell: bash
      run: npm ci
    - name: Lint
      shell: bash
      run: npm run lint
    - name: Commit changes
      shell: bash
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply linting fixes and format code
        ref: ${{ github.ref}}
