import React, { useEffect, useState } from 'react';
import type { TextFieldProps, ButtonProps } from '@mui/material';
import {
  TextField,
  Button,
  Checkbox,
  FormControlLabel,
  Box,
} from '@mui/material';
import { styled } from '@mui/material/styles';

// Todo: Need to add button submit functionality for the user input to be sent to the backend

const UserInputBar = styled(TextField)<TextFieldProps>(({ theme }) => ({
  width: 700,
  color: theme.palette.secondary.main,
  '& .MuiOutlinedInput-root': {
    borderRadius: '20px',
    '& fieldset': {
      borderColor: theme.palette.secondary.main,
      borderRadius: '20px',
    },
    '& input': {
      backgroundColor: theme.palette.grey[200],
      borderRadius: '20px',
    },
  },
}));

const GenerateButton = styled(Button)<ButtonProps>(({ theme }) => ({
  height: 40,
  width: 150,
  color: 'black',
  backgroundColor: theme.palette.secondary.main,
  borderRadius: 20,
  textTransform: 'none',
}));

const PromptInputForm = () => {
  const [isChecked, setIsChecked] = useState(false);

  useEffect(() => {
    const savedCheckedState = localStorage.getItem('isChecked');
    if (savedCheckedState === 'true') {
      setIsChecked(true);
    }
  }, []);

  const handleCheckboxClick = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newCheckedState = event.target.checked;
    setIsChecked(newCheckedState);
    localStorage.setItem('isChecked', newCheckedState.toString());
  };

  return (
    <Box
      display="flex"
      flexDirection="column"
      alignItems="center"
      width="100%"
    >
      <Box width="700px">
        <h2 style={{ textAlign: 'left' }}>Start your learning journey here:</h2>
      </Box>
      <Box
        width="700px"
        display="flex"
        flexDirection="column"
        gap={2}
      >
        <UserInputBar />
        <FormControlLabel
          control={
            <Checkbox
              checked={isChecked}
              onChange={handleCheckboxClick}
              color="primary"
            />
          }
          label="Content on this site may be generated by artifical intelligence (AI). Please use discretion and verify information where necessary."
        />
        <GenerateButton
          disabled={!isChecked}
          sx={{ alignSelf: 'center' }}
        >
          Generate
        </GenerateButton>
      </Box>
      <Box
        width="650px"
        display="flex"
        flexDirection="column"
        marginTop="96px"
      >
        <h2>Popular Topics:</h2>
      </Box>
    </Box>
  );
};

export default PromptInputForm;
