import React, { useState } from 'react';
import type { TextFieldProps, ButtonProps } from '@mui/material';
import {
  TextField,
  Button,
  Checkbox,
  FormControlLabel,
  Box,
} from '@mui/material';
import { styled } from '@mui/material/styles';

const UserInputBar = styled(TextField)<TextFieldProps>(({ theme }) => ({
  width: 700,
  color: theme.palette.secondary.main,
  '& .MuiOutlinedInput-root': {
    '& fieldset': {
      borderColor: theme.palette.secondary.main,
    },
    '& input': {
      backgroundColor: theme.palette.grey[200],
    },
  },
}));

const GenerateButton = styled(Button)<ButtonProps>(({ theme }) => ({
  height: 30,
  width: 150,
  color: 'black',
  backgroundColor: theme.palette.secondary.main,
  textTransform: 'none',
}));

const PromptInputForm = () => {
  const [isChecked, setIsChecked] = useState(false);

  const handleCheckboxClick = (event: React.ChangeEvent<HTMLInputElement>) => {
    setIsChecked(event.target.checked);
  };

  return (
    <div>
      <h2>Start your learning journey here:</h2>
      <Box
        width="700px"
        display="flex"
        flexDirection="column"
        gap={2}
      >
        <UserInputBar />
        <FormControlLabel
          control={
            <Checkbox
              checked={isChecked}
              onChange={handleCheckboxClick}
              color="primary"
            />
          }
          label="Content on this site may be generated by artifical intelligence (AI). Please use discretion and verify information where necessary."
        />
        <GenerateButton
          disabled={!isChecked}
          sx={{ alignSelf: 'center' }}
        >
          Generate
        </GenerateButton>
      </Box>
    </div>
  );
};

export default PromptInputForm;
