name: Deploy to Staging

description: Deploy the bundled file to the staging environment

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20.11.1"

runs:
  using: "ubuntu-latest"
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: BundledFiles
        path: dist
    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat ${{ secrets.SSH_KNOWN_HOSTS }} >> ~/.ssh/known_hosts
        cat >> ~/.ssh/config << END
        Host staging
          HostName ${{ secrets.STAGING_SERVER }}
          User ${{ secrets.SSH_STAGING_USERNAME }}
          IdentityFile ~/.ssh/staging.key
        END
    - name: Move files to Staging
      run: |
        mkdir -p ~/incoming
        scp -r dist ${{ secrets.SSH_STAGING_USERNAME }}@staging:~/incoming
    # stop the server THIS NEEDS TO BE MODIFIED
    - name: Stop Staging Server
      run: |
        ssh staging "sudo systemctl stop node"
    # the following was generated by GitHub Copilot
    - name: Deploy to Staging
      run: |
        ssh staging "cd ~/incoming && tar -xvf dist.tar.gz && rm -rf /var/www/staging/* && mv dist/* /var/www/staging && rm -rf dist && rm -f dist.tar.gz && exit"
    # start the server THIS NEEDS TO BE MODIFIED
    - name: Start Staging Server
      run: |
        ssh staging "sudo systemctl start node"
