# Lint and format files on pull request to dev branch

name: Formatting Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/format
        with:
          node-version: '20.11.1' # The original node version of the project
