# Lint and format files on pull request to dev branch

name: Formatting Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required to push changes back to the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Format
        uses: ./.github/actions/format
        with:
          node-version: '20.11.1' # The original node version of the project
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: format files from GitHub Action'
