name: Server Unit Tests

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server-unit-tests.yml"
  pull_request:
    paths:
      - "server/**"

jobs:
  test:
    name: Server Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          NODE_ENV: test
        run: npm run test:unit --mode unit
