#A basic yaml file to deploy to staging environment

#NOTE: variables currently do not have support, so the strategy matrix
#is reproduced for each job. Hopefully this can be generalized in the future.

name: Deploy to Staging

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  #lint
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint
        with:
          node-version: ${{ matrix.node-version }}

  #test

  #build
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build for Staging
        uses: ./.github/actions/build_for_staging
        with:
          node-version: ${{ matrix.node-version }}

  #deploy to staging
  staging:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Staging
        uses: ./.github/actions/deploy_to_staging
        with:
          node-version: ${{ matrix.node-version }}
